FROM python:3.9
WORKDIR /app
COPY requirements.txt .
COPY . .
RUN pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org --no-cache-dir -r requirements.txt